name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build --verbose --production
      - run: yarn test --production # needs same parameters for build cache to hit
      - run: |
          git config --global user.email "nick.sevens@delaware.pro"
          git config --global user.name "Nick Sevens"
      - run: yarn release -y -r "https://npm.pkg.github.com/" -n $NPM_AUTHTOKEN
        env:
          NPM_AUTHTOKEN: ${{secrets.GITHUB_TOKEN}}
